# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7438e61c1d70c43ac0532fb652b6915c70b665e35b1e0fd47badcb4bc0d68a4fbddd42e5d1979e645684ecd0c0a9888d079d3719341bdae9592c4987280cdc85

test:
  secret_key_base: d82ca84001dc9d2034fd6a0d01fb5149397c64f152519eb97ba91a82127fd391c87dbae35fb32c0f9d17bdb965dac3c764fa36cfeebd808ffc453bf063383987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
